#!/bin/sh -e

if [ "$1" = configure ]; then
#    update-alternatives --install /usr/bin/x-terminal-emulator \
#	x-terminal-emulator /usr/bin/mxterm 45 \
#	--slave /usr/share/man/man1/x-terminal-emulator.1.gz \
#	x-terminal-emulator.1.gz /usr/share/man/man1/mxterm.1.gz
    pkg=tile
fi
